### ISSUE TITLE
when displaying {pIqaD}, non-Klingon text shouldn't be converted

### ISSUE THREAD

**Issue by De7vID** [De7vID/klingon-assistant#140]
This is a problem with the example for the {malja' per} entry, which says:
{Paramount Pictures malja' permey bIH Star Trek pong'e' Deghmey'e' je.}

![image](https://cloud.githubusercontent.com/assets/11312380/12881825/29cb22a4-ce4d-11e5-8c59-fcc6e4d6ca9b.png)

Not clear if this affects anything else.

**Comment by LievenLitaer** [comment]
I do not know of any other examples of this kind. I am not a programmer, but maybe there is a way to add quotes around this to tell the conversion software to skip these words, as in `<nopiqaD>bla</nopiqad>`? On the other side, the converter could be told to skip these three known words, but that may slow it down for all the other entries.
Alternative: write the words as some kind of included code, so that the converter does note see it as words to be converted: `{[c01] malja' permey bIH [c02] pong'e'}`

**Comment by De7vID** [comment]
Closing as only known example is fixed. Reopen if other instances are found.
