### ISSUE TITLE
add other data fields for German in the database

### ISSUE THREAD

**Issue by GoogleCodeExporter** [De7vID/klingon-assistant#25]
```
At the moment, only the only German column in the database is "definition_de".

Add columns at least for "notes_de" and "search_tags_de".
```

Original issue reported on code.google.com by `De.vID.jonpIn` on 8 Jan 2013 at 3:18

**Comment by LievenLitaer** [comment]
When will these be added?

**Comment by De7vID** [comment]
jISovbe'.

**Comment by LievenLitaer** [comment]
So? What can I do to make this happen? Translations seem to be complete by now.

**Comment by De7vID** [comment]
How much time are you willing to invest? It will take a huge effort to translate all the notes.

**Comment by LievenLitaer** [comment]
It's not the question how much time I may be _willing_ to invest, but if I _have_ the time. I know there is lots of information, and I'm sure it will be a very slow and long process. ... But it was also the case with the vocabulary part, so I'm sure we can do this. It would just take a while.
I would suggest that the screen is configured so that it shows the German version if available, and if not, shows the English information. An alternative would be showing nothing, but that may be a loss, since some German users still do understand a little English.

**Comment by De7vID** [comment]
Okay, I've added fields for notes_de and search_tags_de. I think those are the only ones necessary. The only other language-specific field (i.e., field not with data in Klingon) is "hidden_notes", but those are for advanced speakers who in any case must be familiar with the primary sources in English.

Can you translate one entry (or a few entries) which have notes and search tags, so I can test them? Thanks.

**Comment by LievenLitaer** [comment]
been there done that.
