### ISSUE TITLE
Source for jISuDrup

### ISSUE THREAD

**Issue by clsn** [De7vID/klingon-assistant#258]
Not 100% sure, might be able to find out checking records or something, but I think I may have been the inventor of **jISuDrup** for Google's "I'm Feeling Lucky."  Apologies to the real inventor if I'm wrong.

**Comment by De7vID** [comment]
Can you clarify this issue - is it that you want to be credited as the source?

I know who actually entered that translation into Google. That doesn't mean you didn't invent it, since they could've gotten it from you. I don't want to name them publicly here without their consent, but if you email me I can tell you who it is privately and then you can figure out whether they'd gotten it from you or not.

**Comment by De7vID** [comment]
Sent you a private message. Closing this issue.
