### ISSUE TITLE
decouple database from app

### ISSUE THREAD

**Issue by De7vID** [De7vID/klingon-assistant#451]
Make it so that the database can be independently updated from the app. That way, different versions of the app (for different sets of Android APIs, or for iOS) can be updated to the same database.

**Comment by dadap** [comment]
Some considerations:

- It would be nice if the transfer representation could be something more compact like JSON, to save on bandwidth when downloading updates on what might potentially be a metered mobile plan. I think the source format could remain as-is, and the transfer representation could be compiled from the source XML using scripts. Having the transfer representation be different from the source format could be useful in that the transfer representation need not be human-readable and can omit whitespace for further bandwidth savings.
- If the database is more than a few hundred kilobytes in size in its transfer representation, provisions should be made to allow updates without downloading the whole database, either by issuing updates as delta updates (with occasional full database updates if the deltas start approaching some fractional size of the total database or start getting very numerous), or by splitting the database up and publishing a manifest of checksums or other unique versioning identifiers for each part.
- It would be nice to restructure the localized fields to be siblings under a parent non-localized field. For example, instead of <entry><definition/><definition_de></entry>, <entry><definition><en/><de/></definition></entry> would make it easier to add other translations in the future.
- Whatever location hosts the database for downloading to the app should include a version number in part of the database URI, in case a format change is necessary which breaks compatibility with existing clients. The format of the transfer representation need not be correlated with the format of the source representation, and it should be possible to export to multiple different transfer format versions from the same database source.

If the above makes sense, I can put together some scripts to export the XML source to a format like described above and test it out in the Flutter port.

**Comment by De7vID** [comment]
Regarding restructuring the database to put localised siblings under a non-localised parent, the reason it's currently done the way it is is because I'm still supporting legacy versions of the app, which work all the way back to Android API 7. There are actually 3 Android versions of the app, one for API 7+, one for 16+, and one for 23+. At some point, I'll stop supporting the older versions, but they still have users.

It shouldn't be difficult to transform between the old format and a new, better one we can use going forward.

**Comment by dadap** [comment]
Yeah, I noticed the API 7 and API 16 maintenance branches when I was exploring the codebase earlier. That’s part of the reason why I was thinking that the source representation could remain as-is for the time being: the existing tools could continue to be used to export a binary SQLite database to embed into the legacy versions of the app, and those could continue to receive regular (but possibly less frequent) database updates as compared to the current version of the app.

I was thinking it would probably make the most sense to create a new repository with just the history of the KlingonAssistant/data directory (using `git filter-branch --subdirectory-filter` in a clone of klingon-assistant), then replace that directory in the klingon-assistant repository with a git submodule of the new repository. Currently, I have the whole klingon-assistant repository as a submodule in the Flutter port repo; it would be a pretty easy switch to change over to the dedicated database repo once that’s been established.

**Comment by De7vID** [comment]
I've moved the data files into its own repo: [github.com/De7vID/klingon-assistant-data](https://github.com/De7vID/klingon-assistant-data)

**Comment by De7vID** [comment]
Added ability to Android app to update database online here: https://github.com/De7vID/klingon-assistant-android/commit/6a1205c240e981715cfe0b9dac490759184dea59

**Comment by De7vID** [comment]
This ability is in the released versions for both Android and iOS.
