### ISSUE TITLE
Suddenly nothing is found anymore. No results when typing.

### ISSUE THREAD

**Issue by Cyberman-tM** [De7vID/klingon-assistant#466]
I suppose it's an issue with my phone, but restarting didn't help. I can try re-installing it, but before I do that I thought I'd ask here, maybe it's a known situation?

boQwI' 2018.09.02a (db 2018.09.08a)
Android 6.0.1
Phone LG-K500n

I can't say since when exactly this is - there may have been some Android and phone updates in between, I didn't use boQwI' for about a week perhaps.

I can start boQwI' as usual, but when I type anything, nothing happens - when I press enter, it says it didn't find any results, even if I look for words like tlhIngan, or be' .

My feeling is that somehow it doesn't have access to the databse anymore, since the error message seems to indicate that the search itself works.

I have no idea how that could be, though - I certainly didn't change anything knowingly, all I do is install updates when they arrive - I didn't even try out different apps recently...

**Comment by De7vID** [comment]
I think there's a race condition since the database size has increased (because of the addition of new languages), between updating and reading the database. So under some conditions, the old database gets wiped but the new one doesn't get written. But I don't know what those conditions are to reproduce them.

Can you go into "App Info" and see how much storage is being used (app size, user data, and also cache). You can then try to clear the data (though this will erase your settings) and see if that forces the database to be rewritten.

**Comment by Cyberman-tM** [comment]
"10.53MB used in internal storage"
I think that's what you mean?

OK, data cleared - lost all settings (was warned about it), I don't think I even HAVE settings :-)

And, now it works again - result suggestions come immediately, results work perfectly.

Thanks!
