### ISSUE TITLE
Update Chrome OS App

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [De7vID/klingon-assistant#480]
The Chrome OS App was last updated in 2017. Could you update it to a current version?
https://chrome.google.com/webstore/detail/boqwi/bfahgkmmeilabbfdhacmeakehfcpgcej

**Comment by De7vID** [comment]
Chrome OS has supported native Android apps since at least version 53. I've left the Chrome Web Store version online in case anyone is still running an old version of Chrome OS for some reason, but I can no longer update the app, and in fact, it is scheduled to be deleted soon.

<img width="913" alt="Screenshot 2020-04-21 at 07 24 57" src="https://user-images.githubusercontent.com/11312380/79828574-3fb4ac80-83a1-11ea-97a8-108fe16e1fe0.png">

Is there some reason you need to run a newer version of **boQwI'** on an old OS?

**Comment by TheOneWithTheBraid** [comment]
My problem is I don't use boQwI' on a device allowed to run Android apps. Means I have a current version of Chromium OS but without the authorization of Google to download the Android runtimes. This usually applies if you use the open source version of Chromium OS.

**Comment by TheOneWithTheBraid** [comment]
My problem is I don't use boQwI' on a device allowed to run Android apps. Means I have a current version of Chromium OS but without the authorization of Google to download the Android runtimes. This usually applies if you use the open source version of Chromium OS.

**Comment by De7vID** [comment]
But if you use the open source version of Chromium OS, you can still access the Chrome Web Store?

In any case, like I said, support is being removed and I cannot update the app.
