### ISSUE TITLE
Option to screensaver

### ISSUE THREAD

**Issue by LievenLitaer** [De7vID/klingon-assistant#481]
Several apps have the option to override the screensaver function, if it would be useless turning of the screen when reading a page or viewing a video.
Reason for request: I have my screensaver set to a timeout of 1 minute or so. While working on a Klingon text it would be useful if the app just remained open, staying awake, even if it's unattended longer than my screensaver settings.

**Comment by De7vID** [comment]
You can do this with another app dedicated to keeping the screen awake. It's actually a bad idea to add system functionality unrelated to an app to the app, as it causes code bloat. It would mean that **boQwI'** would require systems permissions it wouldn't need otherwise, and be associated with increased battery and CPU usage.

Usually, doing something like adding systems permissions to an app will cause fewer people to download it and leave comments saying the app might be doing things it isn't doing. That alone is reason not to do this.

**Comment by ChKargh** [comment]
> You can do this with another app dedicated to keeping the screen awake. It's actually a bad idea to add system functionality unrelated to an app to the app, as it causes code bloat. It would mean that **boQwI'** would require systems permissions it wouldn't need otherwise, and be associated with increased battery and CPU usage.
> 
> Usually, doing something like adding systems permissions to an app will cause fewer people to download it and leave comments saying the app might be doing things it isn't doing. That alone is reason not to do this.

you looks familiar.

**Comment by LievenLitaer** [comment]
> That alone is reason not to do this.

Alright, that makes sense. I was not aware of those consequences. Case closed for me.

**Comment by ChKargh** [comment]
Hoy Lieven
